---
title: "CodeBook"
author: "Davis Clark"
date: "Saturday, April 25, 2015"
output: html_document
---

Human Activity Recognition experiments were carried out with a group of 30 volunteers, within an age range of 19-48 years. Each person performed six activities (**walking**, **walkingup**, **walkingdown**, **sitting**, **standing**, **laying**), wearing a smartphone (Samsung Galaxy S II) on the waist. Using the phone's embedded accelerometer and gyroscope, the experiment captured **3-axial linear acceleration and 3-axial angular velocity, at a constant rate of 50Hz**. The dataset was randomly partitioned into two sets; 70% of volunteer data was used to generate a training set, while the remaining data went into a testing set. 

The sensor signals (accelerometer (`acc`) and gyroscope (`gyro`)) were pre-processed, using noise filters, and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window).  

The sensor acceleration signal, which has gravitational and body motion components, was separated into body acceleration (`bodyacc`) and gravity acceleration (`gravityacc`), using a Butterworth low-pass filter. The gravitational force is assumed to have only low frequency components; therefore, a filter with 0.3 Hz cutoff frequency was used. 

A vector of features was obtained, by calculating variables from the time domain (prefix `t-`) and frequency domain (prefix `f-`) of each window.

**For each record it is provided:**

- An identifier of the subject who carried out the activity
- An activity label
- A feature factor, indicating the measurement summarized
- A mean value, presenting the average measurement recorded for the particular subject, activity, feature combination

**Notes**: variables are normalized and bounded within [-1,1]

##Code book

###Domain

- **t-**: time domain  
- **f-**: frequency domain  

###Signals  
 
- **t_bodyacc**:  
Time domain body acceleration signal  
(derived from acceleration signal)  
**Note**: **-X**, **-Y**, **-Z** is used to denote the 3-axial signal in the X, Y, or Z direction 

- **t_bodyaccmag**:  
Magnitude of time domain body acceleration signal  
(calculated using the Euclidean norm)  
**Note**: **-X**, **-Y**, **-Z** is used to denote the 3-axial signal in the X, Y, or Z direction 

- **t_bodyaccjerk**:  
Time domain body acceleration jerk signal  
(derived from body linear acceleration)  
**Note**: **-X**, **-Y**, **-Z** is used to denote the 3-axial signal in the X, Y, or Z direction 

- **t_bodyaccjerkmag**:   
Magnitude of time domain body acceleration jerk signal  
(calculated using the Euclidean norm) 

- **t_gravityacc**:  
Time domain gravity acceleration signal  
(derived from acceleration signal)  

- **t_gravityaccmag**:   
Magnitude of time domain gravity acceleration signal  
(calculated using the Euclidean norm)   
 
- **t_bodygyro**:  
Time domain body gyroscope signal  
(derived from gyroscope signal)  

- **t_bodygyromag**:  
Magnitude of time domain body gyroscope signal  
(calculated using the Euclidean norm)  
  
- **t_bodygyrojerk**:  
Time domain body gyroscope jerk signal  
(derived from angular velocity)  
   
- **t_bodygyrojerkmag**:  
Magnitude of time domain body gyroscope jerk signal  
(calculated using the Euclidean norm)  
  
- **f_bodyacc** (*prefix 'f' to denote time*):  
Frequency domain body acceleration signal  
(produced using Fast Fourier Transform (FFT))  
   
- **f_bodyaccjerk**:  
Frequency domain body acceleration jerk signal  
(produced using Fast Fourier Transform (FFT)) 

- **f_bodyaccjerkmag**:  
Magnitude of frequency domain body acceleration jerk signal  
(produced using Fast Fourier Transform (FFT)) 
  
- **f_bodygyro**:  
Frequency domain body gyroscope signal  
(produced using Fast Fourier Transform (FFT))  
  
- **f_bodygyromag**:  
Magnitude frequency domain body gyroscope signal  
(produced using Fast Fourier Transform (FFT))  
  
- **f_bodygyrojerkmag**:  
Magnitude of frequency domain body gyroscope jerk signal  
(produced using Fast Fourier Transform (FFT))  
  
###Measurements
The set of measurements estimated from these signals are:  

- **-mean-**: mean value  
- **-std-**: standard deviation 

###Feature syntax
  
**domain** _ **signal** _ **measure** _ **axial-direction**  

For example:  
  
- **t_bodyacc_mean_x**
